export const siteConfig = {
  name: "Sipi & Noir",
  metaTitle: "Premium Men's Jackets – All Types of Jackets",
  tagline: "Premium Jackets for Men",
  description:
    "Discover premium lightweight jackets for men. Training jackets and windcheaters engineered for movement, comfort, and everyday urban style.",
  url: "https://sipinoir.com",
  ogImage: "/images/og-image.svg",
  logo: "/logo.png",
  twitterHandle: "@sipinoir",
  keywords: [
    "jacket",
    "jackets",
    "premium jackets",
    "outerwear",
    "men's jackets",
    "women's jackets",
    "urban fashion",
    "outdoor jackets",
    "winter jackets",
    "fashion",
    "clothing brand",
    "sustainable fashion",
    "quality jackets",
  ],
  authors: [{ name: "Sipi & Noir Team", url: "https://sipinoir.com/about" }],
  creator: "Sipi & Noir",
  themeColor: "#1a0a0a",
};
